name: Main

on: [push, pull_request]

jobs:
  linting:
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.19.4
      - name: Run analysis
        run: flutter analyze
