name: Main

on: push

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.19.4
      - name: Run analysis
        run: flutter analyze

  formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.19.4
      - name: Check formatting
        run: dart format --set-exit-if-changed .

  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.19.4
      - name: Run tests
        run: flutter test

  integration-testing:
    runs-on: macos-latest
    environment: Main
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.19.4
      - name: Create env file
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }}
        run: printenv ENV_FILE > env.json
      - name: Set up simulator
        uses: futureware-tech/simulator-action@v3
        with:
          model: "iPhone 15"
      - name: Run tests
        run: flutter test integration_test --dart-define-from-file=env.json

  building-android:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.19.4
      - name: Generates appbundle
        run: flutter build appbundle
      - name: Uploads appbundle
        uses: actions/upload-artifact@v4
        with:
          name: appbundle
          path: build/app/outputs/bundle/release/app-release.aab

  building-ios:
    runs-on: macos-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.19.4
      - name: Generates ipa
        run: flutter build ipa --no-codesign
      - name: Uploads ipa
        uses: actions/upload-artifact@v4
        with:
          name: ipa
          path: build/ios/archive/Runner.xcarchive/
